### ISSUE TITLE
utterances test

### ISSUE THREAD

**Issue by cwc329** [Lidemy/error-baker-blog#13]
test utterances

**Comment by cwc329** [comment]
test comment

**Comment by cwc329** [comment]
comment

**Comment by cwc329** [comment]
description 太常導致 query string 爆掉讓 session 無法用。

**Comment by aszx87410** [comment]
應該不是 desc 太長，是因為 main.js 開頭有一段會把 query string 清掉，這我之後處理一下

**Comment by cwc329** [comment]
所以這個問題有再出現嗎？
我看好像是好的

**Comment by aszx87410** [comment]
我這邊試是有問題，我猜可能跟 chrome 版本有關吧？或也有可能不一定可以穩定重現

總之問題出在這一段：https://github.com/utterance/utterances/blob/master/src/client.ts#L7
會從 query string 拿 session 出來寫到 localStorage
但是這一段會自動把 query string 清掉，造成 utter 拿不到：https://github.com/Lidemy/error-baker-blog/blob/main/src/main.js#L23

我後來的做法是把 utter 清掉那段的 replaceState 加上 setTimeout 1 秒，讓他 1 秒後再清除
