### ISSUE TITLE
使用 Summary 標籤的文章和沒有使用的文章有不同的 style 

### ISSUE THREAD

**Issue by keronscribe** [Lidemy/error-baker-blog#32]
手機版對照
<img width="430" alt="スクリーンショット 2021-08-12 23 54 16" src="https://user-images.githubusercontent.com/34278495/129219038-77e7b3b0-bb85-4395-9ecd-682c00fb0f58.png">
<img width="490" alt="スクリーンショット 2021-08-12 23 55 08" src="https://user-images.githubusercontent.com/34278495/129219190-63e2de33-bc67-4a5f-aea2-b73db47ef28a.png">

網頁版對照
<img width="1438" alt="スクリーンショット 2021-08-12 23 55 24" src="https://user-images.githubusercontent.com/34278495/129219233-9d2db00c-bbee-4645-9365-87d9658548ad.png">
<img width="1440" alt="スクリーンショット 2021-08-12 23 55 41" src="https://user-images.githubusercontent.com/34278495/129219270-2843ccb1-66e0-4325-9251-4161d8279348.png">

問題點：
- 字體大小不同
- article margin 不同
-  有 summary 的內容在手機版上字體會過小

已知` <head>` 中帶的  `<style>` 標籤內容不同，初步查看 HTML 結構應該沒有不一致，把沒有 `<!--summary-->` 文章的 `<style>` 標籤內容搬移進有 `<!--summary-->` 的文章中，版面就會一致了。需要進一步決定對策。

**Comment by aszx87410** [comment]
修掉囉：https://github.com/Lidemy/error-baker-blog/commit/a3298756333ecc3f42ac69e9589b0bf8c0526383

沒仔細研究但我猜這套 blog 有個 plugin 會刪掉沒用到的 css，有 summary 的才會被判斷有用到然後才會套用到 `--p` 的 css，我稍微修了一下，覺得字體太小的話再看 @ishin4554 想怎麼調
