### ISSUE TITLE
分享功能

### ISSUE THREAD

**Issue by aszx87410** [Lidemy/error-baker-blog#6]
目前右下角有個很佔位的 icon，文章最底下有個點了可以複製的按鈕
想改成原生的 share API; https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

**Comment by ishin4554** [comment]
@aszx87410 這邊可能不需要調整，根據 main.js 中的 share function 來看，原本已經是使用原生的 share API，
https://github.com/Lidemy/error-baker-blog/blob/47e33ee6f1991a0bb94bcca5789688f9822d69c6/src/main.js#L41

猜測是因為目前 share API 支援的範圍非常有限，根據 MDN 來看，如果是用 macos chrome 開啟可能會看不見：
![image](https://user-images.githubusercontent.com/10834433/125168342-ba046300-e1d7-11eb-9852-8703018fc91b.png)

重新用 safari 測試是可以使用 share API 確認原本 11ty 就有實作：
![image](https://user-images.githubusercontent.com/10834433/125168406-0ea7de00-e1d8-11eb-9f6a-0eafa7c12db9.png)

**Comment by aszx87410** [comment]
原來是這樣！我在 mac 上的確是複製，用 android 看是分享沒錯，那好像不需要調整了，頂多調一些按鈕的樣式？右下角那個 fixed 的按鈕
